Repository Tech-Community-Peru/tech-events-api, pull requests merged in 2024-10, with the labels that each got.

#39 fix(Backend): Se implemento las anotaciones del docente
  DIAGRAMA BASE DE DATO.png
  DIAGRAMA CLASE.png
  README.md
  img.png
  img_1.png
  img_2.png
  img_3.png
  img_4.png
  src/main/java/com/techcommunityperu/techcommunityperu/api/AuthController.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Ganador.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Inscripcion.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Participante.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Roles.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Sorteo.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Usuario.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/usuarioComunidad.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/enums/categoryEvent.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/InscripcionRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/InscriptionRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/UserRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/EmailServiceImpl.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/InscripcionServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/data-test.sql
Labels: Backend, Fix, Sprint 02

#40 Feature/filtrado categoria
  src/main/java/com/techcommunityperu/techcommunityperu/api/EventoController.java
  src/main/java/com/techcommunityperu/techcommunityperu/config/ModelMapper.java
  src/main/java/com/techcommunityperu/techcommunityperu/config/ModelMapperConfig.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/EventoResDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Ponente.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/EventRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/EventService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/EventServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/data-test.sql
Labels: Backend, Sprint 02

#43 Feature/payment method security
  src/main/java/com/techcommunityperu/techcommunityperu/api/InscripcionController.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/InscripcionDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/exception/GlobalExceptionHandler.java
  src/main/java/com/techcommunityperu/techcommunityperu/exception/ResourceNotFoundException.java
  src/main/java/com/techcommunityperu/techcommunityperu/mapper/InscripcionMapper.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/InscripcionRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/UsuarioRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/InscripcionService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/PaymentSecurityService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/InscripcionServiceImpl.java
  src/main/resources/application.properties
Labels: Backend, Sprint 02

#41 Feature/community management
  src/main/java/com/techcommunityperu/techcommunityperu/api/AuthController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/CommunityController.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/CommunityDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/exception/MissingFieldsException.java
  src/main/java/com/techcommunityperu/techcommunityperu/exception/ResourceNotFoundException.java
  src/main/java/com/techcommunityperu/techcommunityperu/mapper/CommunityMapper.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/CommunityRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/UsuarioComunidadRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/CommunityService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/UserService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/CommunityServiceImpl.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/UserServiceImpl.java
  src/main/resources/application.properties
Labels: Backend, Sprint 02

#44 Feature/filter user event
  pom.xml
  qr_codes/qr_1_1.png
  src/main/java/com/techcommunityperu/techcommunityperu/api/CustomExceptionHandler.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/EventoController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/InscripcionController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/QRCodeController.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/EventoDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/EventoFiltroDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Comentario.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Evento.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Inscripcion.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/CronogramaRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/InscriptionRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/EventService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/InscripcionService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/QRCodeService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/EventServiceImpl.java
  src/main/resources/application.properties
Labels: Backend, Sprint 01

#45 feat(backend): Implementacion crud de cronograma
  src/main/java/com/techcommunityperu/techcommunityperu/api/CronogramaController.java
  src/main/java/com/techcommunityperu/techcommunityperu/exceptions/BadRequestException.java
  src/main/java/com/techcommunityperu/techcommunityperu/exceptions/GlobalExceptionHandler.java
  src/main/java/com/techcommunityperu/techcommunityperu/exceptions/ResourceNotFoundException.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/CronogramaRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/CronogramaService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/CronogramaServiceImpl.java
Labels: Backend, Sprint 02

#46 Feature/reporte asistencia
  src/main/java/com/techcommunityperu/techcommunityperu/api/ReporteAsistenciaController.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/AsistenciaDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/exceptions/BadRequestException.java
  src/main/java/com/techcommunityperu/techcommunityperu/exceptions/ResourceNotFoundException.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Asistencia.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Evento.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/AsistenciaRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/EventRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/ReporteAsistenciaService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/ReporteAsistenciaServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/data-test.sql
Labels: Backend, Sprint 02

#47 feat(Backend): historias de usuario de listar eventos por id de parti…
  src/main/java/com/techcommunityperu/techcommunityperu/api/ActivityUserController.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/EventoDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Inscripcion.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/InscriptionRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/InscripcionService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/EmailServiceImpl.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/InscripcionServiceImpl.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/PurchaseServiceImpl.java
  src/main/resources/data-test.sql
Labels: Backend, Sprint 01

#48 feat(Backend):Gestion-Sorteos_eventos
  src/main/java/com/techcommunityperu/techcommunityperu/api/PurchaseController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/SorteoController.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/CrearSorteoDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/GanadorDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/SorteoDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/exceptions/FechaPasadaException.java
  src/main/java/com/techcommunityperu/techcommunityperu/exceptions/InscripcionesInsuficientesException.java
  src/main/java/com/techcommunityperu/techcommunityperu/exceptions/InvalidPaymentTypeException.java
  src/main/java/com/techcommunityperu/techcommunityperu/exceptions/SorteoExistenteException.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Ganador.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Sorteo.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/enums/paymentType.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/GanadorRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/InscriptionRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/SorteoRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/GanadorService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/PurchaseService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/SorteoService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/GanadorServiceImpl.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/PurchaseServiceImpl.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/SorteoServiceImpl.java
  src/main/resources/data-test.sql
Labels: Backend, Sprint 02

#49 Feature/gestion perfil
  src/main/java/com/techcommunityperu/techcommunityperu/api/AccountController.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/enums/Role.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/ParticipantRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/RolesRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/AccountParticipantService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/AccountParticipantServiceImpl.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/UserServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/data-test.sql
Labels: Backend, Sprint 02

#51 Feature/subir y mostrar archivos api
  qr_codes/qr_1_1.png
  src/main/java/com/techcommunityperu/techcommunityperu/api/InscripcionController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/MediaController.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/EventoResDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/InscripcionDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/ParticipanteDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/UploadMediaDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/UsuarioDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/mapper/EventoMapper.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Evento.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/ComentarioService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/StorageService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/FileSystemStorageService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/InscripcionServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/data-test.sql
Labels: Backend

#52 feat(backend): Correción de las clases QR y Comentarios
  src/main/java/com/techcommunityperu/techcommunityperu/api/ComentarioController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/QRCodeController.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/ComentarioRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/ParticipantRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/ComentarioService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/QRCodeService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/ComentarioServiceImpl.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/QRCodeServiceImpl.java
  src/main/resources/application.properties
Labels: Backend, Sprint 02

#55 Feature/paypal api
  src/main/java/com/techcommunityperu/techcommunityperu/api/CheckoutController.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/PaymentCaptureResponse.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/PaymentOrderResponse.java
  src/main/java/com/techcommunityperu/techcommunityperu/integration/payment/paypal/dto/Amount.java
  src/main/java/com/techcommunityperu/techcommunityperu/integration/payment/paypal/dto/ApplicationContext.java
  src/main/java/com/techcommunityperu/techcommunityperu/integration/payment/paypal/dto/ExperienceContext.java
  src/main/java/com/techcommunityperu/techcommunityperu/integration/payment/paypal/dto/Link.java
  src/main/java/com/techcommunityperu/techcommunityperu/integration/payment/paypal/dto/OrderCaptureResponse.java
  src/main/java/com/techcommunityperu/techcommunityperu/integration/payment/paypal/dto/OrderRequest.java
  src/main/java/com/techcommunityperu/techcommunityperu/integration/payment/paypal/dto/OrderResponse.java
  src/main/java/com/techcommunityperu/techcommunityperu/integration/payment/paypal/dto/PaymentSource.java
  src/main/java/com/techcommunityperu/techcommunityperu/integration/payment/paypal/dto/Paypal.java
  src/main/java/com/techcommunityperu/techcommunityperu/integration/payment/paypal/dto/PurchaseUnit.java
  src/main/java/com/techcommunityperu/techcommunityperu/integration/payment/paypal/dto/TokenResponse.java
  src/main/java/com/techcommunityperu/techcommunityperu/integration/payment/paypal/service/PayPalService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/CheckoutService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/PurchaseService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/CheckoutServiceImpl.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/PurchaseServiceImpl.java
  src/main/resources/application.properties
Labels: Backend, Sprint 02

#56 feat(Backend) : Tokens y Autenticacion terminado
  src/main/java/com/techcommunityperu/techcommunityperu/api/AuthController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/ComentarioController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/InscripcionController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/MediaController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/UserProfileController.java
  src/main/java/com/techcommunityperu/techcommunityperu/config/SwaggerApiConfig.java
  src/main/java/com/techcommunityperu/techcommunityperu/config/WebSecurityConfig.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/AuthResponseDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/LoginDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/mapper/UsuarioMapper.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Participante.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Usuario.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/ParticipantRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/security/CustomUserDetailsService.java
  src/main/java/com/techcommunityperu/techcommunityperu/security/UserPrincipal.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/UsuarioService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/UsuarioServiceImpl.java
  src/main/resources/application.properties
Labels: Backend, Sprint 02

#61 Fix/enviar email cronograma
  src/main/java/com/techcommunityperu/techcommunityperu/repository/CronogramaRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/ParticipantRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/PonenteRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/CronogramaService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/UsuarioService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/CheckoutServiceImpl.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/CronogramaServiceImpl.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/UsuarioServiceImpl.java
  src/main/resources/templates/confirmation-template.html
Labels: Backend, Fix

#60 Feature/analisis
  src/main/java/com/techcommunityperu/techcommunityperu/api/AsistenciaController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/EstadisticasController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/QRCodeController.java
  src/main/java/com/techcommunityperu/techcommunityperu/config/WebSecurityConfig.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/ParticipanteActivoDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Inscripcion.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/RegistroEscaneo.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/AsistenciaRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/RegistroEscaneoRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/EstadisticasService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/EstadisticasServiceImpl.java
  src/main/resources/application.properties
Labels: Backend

#63 Feature/password reset token
  src/main/java/com/techcommunityperu/techcommunityperu/api/EmailController.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/PasswordResetToken.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/PasswordResetTokenRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/PasswordResetTokenService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/PasswordResetTokenServiceImpl.java
  src/main/resources/templates/reset-password.html
Labels: Backend, Sprint 02

#62 fix(Backend):Eliminar-User
  src/main/java/com/techcommunityperu/techcommunityperu/repository/AsistenciaRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/UserCommunityRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/AccountParticipantServiceImpl.java
  src/main/resources/application.properties
Labels: Backend, Fix
