Repository Tech-Community-Peru/tech-events-api, pull requests merged in 2024-11, with the labels that each got.

#66 fix(Backend): regresado a version estable
  src/main/java/com/techcommunityperu/techcommunityperu/api/auth/AccountController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/auth/AuthController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/community/ComentarioController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/email/EmailController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/event/CronogramaController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/event/EventoController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/event/InscripcionController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/event/SorteoController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/exception/CustomExceptionHandler.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/media/MediaController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/media/QRCodeController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/purchase/CheckoutController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/purchase/PurchaseController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/report/EstadisticasController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/report/ReporteAsistenciaController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/user/ActivityUserController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/user/AsistenciaController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/user/CommunityController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/user/UserProfileController.java
Labels: Backend

#67 feat(Backend): Listar todos los eventos logrado
  src/main/java/com/techcommunityperu/techcommunityperu/api/event/EventoController.java
  src/main/java/com/techcommunityperu/techcommunityperu/mapper/EventoMapper.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/EventService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/EventServiceImpl.java
Labels: Backend

#69 Feature/inscripcion a
  src/main/java/com/techcommunityperu/techcommunityperu/api/event/EventoController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/event/InscripcionController.java
  src/main/java/com/techcommunityperu/techcommunityperu/config/CORSConfig.java
  src/main/java/com/techcommunityperu/techcommunityperu/config/WebSecurityConfig.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/AuthResponseDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/UsuarioPerfilDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/mapper/UsuarioMapper.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/InscripcionService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/InscripcionServiceImpl.java
Labels: Backend

#71 Feature/inscripcion evento
  src/main/java/com/techcommunityperu/techcommunityperu/api/event/InscripcionController.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/AuthResponseDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/mapper/UsuarioMapper.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Participante.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/InscriptionRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/PurchaseServiceImpl.java
Labels: Backend, Fix

#72 Feature/send qr inscription
  src/main/java/com/techcommunityperu/techcommunityperu/service/PurchaseService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/FavoritosServiceImpl.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/PurchaseServiceImpl.java
  src/main/resources/data-test.sql
  src/main/resources/qrCodes/inscripcion_9.png
  src/main/resources/templates/confirmation-template.html
  src/main/resources/templates/invitacion-send.html
Labels: Backend

#73 Feature/qr code in email
  src/main/java/com/techcommunityperu/techcommunityperu/api/purchase/PurchaseController.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/QRDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/integration/email/impl/EmailServiceImpl.java
  src/main/java/com/techcommunityperu/techcommunityperu/integration/email/service/EmailService.java
  src/main/java/com/techcommunityperu/techcommunityperu/mapper/QRMapper.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Comunidad.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Evento.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/PurchaseService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/FavoritosServiceImpl.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/PurchaseServiceImpl.java
  src/main/resources/data-test.sql
  src/main/resources/templates/confirmation-template.html
  src/main/resources/templates/invitacion-send.html
Labels: Backend, Fix

#76 Develop : put y post evento
  src/main/java/com/techcommunityperu/techcommunityperu/api/event/EventoCreateCrontroller.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/EventoCreateDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/mapper/EventoMapper.java
  src/main/java/com/techcommunityperu/techcommunityperu/model/entity/Ubicacion.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/CommunityRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/EventoCreateRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/PonenteRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/repository/UbicacionRepository.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/EventoCreateService.java
  src/main/java/com/techcommunityperu/techcommunityperu/service/impl/EventoCreateServiceImpl.java
  src/main/resources/templates/confirmation-template.html
  src/main/resources/templates/invitacion-send.html
Labels: Backend, Deploy

#78 Feature/logearse una vez
  src/main/java/com/techcommunityperu/techcommunityperu/api/event/InscripcionController.java
  src/main/java/com/techcommunityperu/techcommunityperu/api/user/ActivityUserController.java
  src/main/java/com/techcommunityperu/techcommunityperu/dto/AuthResponseDTO.java
  src/main/java/com/techcommunityperu/techcommunityperu/mapper/UsuarioMapper.java
Labels: Backend, Fix
